### PR TITLE
[feature] use Remarkable to render markdown

### PR DESCRIPTION
**Pull request by szdytom**

### CODE REVIEW

**Review by gzezFISHER — DISMISSED** [review]

**Review by gzezFISHER — DISMISSED** [review]

**Review by zhangtianli2006 — DISMISSED** [review]

**Comment by szdytom** [comment]
Wait a minute, they're conflicts. I'am solving this!!!

**Comment by zhangtianli2006** [comment]
What the freak are you doing??

**Comment by szdytom** [comment]
You cannot rebase and merge if you use `Update Branch`!! Let me show you

**Review by zhangtianli2006 — APPROVED** [review]

**Comment by szdytom** [comment]
This is how problem get solved. If you didn't operate, I'll be able to solve it with only force-pushing once.

**Pull request merged**
