### PR TITLE
[feature] code mirror in problem submit

### PR DESCRIPTION
**Pull request by zhangtianli2006**
Signed-off-by: zhangtianli2006 <zhangtianli2006@163.com>

### CODE REVIEW

**Review by szdytom — COMMENTED** [review]
You'd better allow not to enable CodeMirror in user's settings.

**Comment by zhangtianli2006** [comment]
If you already allowed CM to load in the problem edit page by default, then what's the problem of loading it in the problem submit page.
Also, CM should be downloaded into the browser's cache when opening up the homepage since it's a node component.

**Comment by zhangtianli2006** [comment]
But I can do a checkbox to let the user choose, commit later.

**Review by szdytom — APPROVED** [review]
OK. Everything is well except for your miss-spelled commit message.

BTW: How's the Judger Leader?

**Comment by zhangtianli2006** [comment]
> OK. Everything is well except for your miss-spelled commit message.
> 
> BTW: How's the Judger Leader?

Not possible when you have two classes per day.

**Pull request merged**
