### PR TITLE
display markdown and code highlight correctly

### PR DESCRIPTION
**Pull request by szdytom**
Sorry I deleted add-hljs-ztl by mistake.
Now I add it back...

### CODE REVIEW

**Comment by szdytom** [comment]
I don't know how to change escaped char like `&lt;` back to normal in code

**Comment by szdytom** [comment]
Wht not to render markdown in the frontend? I saw no security reason, nor any other reason.

**Comment by szdytom** [comment]
OK, I change markdown rendering to the frontend, everything seems prefect.
(I'll soon update the backend

**Comment by szdytom** [comment]
Oh, now `allow_html` takes no effect. I'll fix it

**Comment by szdytom** [comment]
ok now.
but...marked tell me sanitize in deprecated.I'll change to DOMPurify or something like this...

**Comment by zhangtianli2006** [comment]
Hope to fix soon, I'm going to add some styles,
please be as quick as possible,
you can to leave some strange errs behind

**Pull request merged**
